# Generated by Django 3.0.7 on 2020-06-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=25)),
            ],
        ),
    ]
