# Generated by Django 3.0.7 on 2020-06-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gps',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gps',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True),
        ),
    ]
