# Generated by Django 3.0.7 on 2020-06-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_gps_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='_id',
            field=models.CharField(max_length=20),
        ),
    ]
